version: "3"

services:
  app:
    build: . 
    ports:
      - "80:80"
    depends_on:
      - "composer"

  composer:
    image: composer:latest
    command: install
    volumes:
      - ./src:/app
